/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-09-04 13:26:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_005floggedin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1534674664000L));
    _jspx_dependants.put("jar:file:/home/bill/Desktop/linkedin%20workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LinkedInClone/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153374282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html>\n");
      out.write("<title>WorkConnect - Admin</title>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/w3.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/w3-theme-blue-grey.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"fonts/open_sans.ttf\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\n");
      out.write("<style>\n");
      out.write("    html,\n");
      out.write("    body,\n");
      out.write("    h1,\n");
      out.write("    h2,\n");
      out.write("    h3,\n");
      out.write("    h4,\n");
      out.write("    h5 {\n");
      out.write("        font-family: \"Open Sans\", sans-serif\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<body class=\"w3-theme-l5\">\n");
      out.write("    <!-- Navbar -->\n");
      out.write("    <div class=\"w3-top\">\n");
      out.write("        <div class=\"w3-bar w3-theme-d3 w3-left-align w3-large\">\n");
      out.write("            <a class=\"w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-large\" href=\"javascript:void(0);\"\n");
      out.write("                onclick=\"openNav()\">\n");
      out.write("                <i class=\"fa fa-bars\"></i>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"admin.html\" class=\"w3-bar-item w3-button w3-padding-large\">\n");
      out.write("\n");
      out.write("                WorkConnect - Admin Control Page\n");
      out.write("            </a>\n");
      out.write("            <a href=\"login.html\" class=\"w3-bar-item w3-button w3-hide-small w3-right w3-padding-large\">\n");
      out.write("                <i class=\"fa fa-sign-out\"></i>\n");
      out.write("                Log Out\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Navbar on small screens -->\n");
      out.write("    <div id=\"navDemo\" class=\"w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium w3-large\">\n");
      out.write("        <a href=\"admin.html\" class=\"w3-bar-item w3-button w3-padding-large\">Home</a>\n");
      out.write("        <a href=\"login.html\" class=\"w3-bar-item w3-button w3-padding-large\">Log Out</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Page Container -->\n");
      out.write("    <div class=\"w3-container w3-content\" style=\"max-width:66.%;margin-top:80px\">\n");
      out.write("        <!-- The Grid -->\n");
      out.write("        <div class=\"w3-row\">\n");
      out.write("\n");
      out.write("            <!-- Middle Column -->\n");
      out.write("            <div class=\"w3-col\">\n");
      out.write("                <div class=\"w3-container w3-card w3-white w3-margin\">\n");
      out.write("                    <table style=\"width: 100%\">\n");
      out.write("                        <td style=\"width: 37%\">\n");
      out.write("                            <h4>\n");
      out.write("                                <i class=\"fa fa-user\"></i> Users</h4>\n");
      out.write("                        </td>\n");
      out.write("                        <td style=\"width: 17%\">\n");
      out.write("                            <button type=\"button\" onclick=\"unselect_all();\" class=\"w3-button w3-theme-d2 w3-margin-right\">\n");
      out.write("                                <i class=\"fa fa-remove\"></i> Unselect All</button>\n");
      out.write("                        </td>\n");
      out.write("                        <td style=\"width: 23%\">\n");
      out.write("                            <button type=\"button\" class=\"w3-button w3-theme-d2 w3-margin-right\">\n");
      out.write("                                <i class=\"fa fa-download\"></i> Download Selected (XML)</button>\n");
      out.write("                        </td>\n");
      out.write("                        <td style=\"width: 23%\">\n");
      out.write("                            <button type=\"button\" class=\"w3-button w3-theme-d2\" style=\"width: 100%\">\n");
      out.write("                                <i class=\"fa fa-download\"></i> Download All (XML)</button>\n");
      out.write("                        </td>\n");
      out.write("                    </table>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"w3-container w3-card w3-white w3-margin\">\n");
      out.write("                    <table style=\"width: 100%\">\n");
      out.write("                        <td>\n");
      out.write("                            <p class=\"w3-center\">\n");
      out.write("                                <a href=\"profile_admin.html\">\n");
      out.write("                                    <img src=\"images/avatar2.png\" style=\"height:116px;width:116px\" alt=\"Avatar\">\n");
      out.write("                                </a>\n");
      out.write("                            </p>\n");
      out.write("                        </td>\n");
      out.write("                        <td class=\"w3-padding\">\n");
      out.write("                            <h4 class=\"w3-center\"><a href=\"user_profile.html\" class=\"w3-link\">Profile #1</a></h4>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-pencil fa-fw w3-margin-right w3-text-theme\"></i> Designer, UI</p>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-home fa-fw w3-margin-right w3-text-theme\"></i> London, UK</p>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme\"></i> April 1, 1988</p>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-envelope-open\"></i> Email: email@gmail.com</p>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-phone\"></i> Phone: +123456789</p>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-link\"></i> Website: website.com</p>\n");
      out.write("                            </p>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <div style=\"width:100%\">\n");
      out.write("                                <table style=\"width:100%\">\n");
      out.write("                                    <td style=\"width:100%\">\n");
      out.write("                                        <label class=\"w3-opacity-min\">Select User (XML) </label>\n");
      out.write("                                    </td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input id=\"check_1\" class=\"w3-check\" type=\"checkbox\">\n");
      out.write("                                    </td>\n");
      out.write("                                </table>\n");
      out.write("                            </div>\n");
      out.write("                            <button type=\"button\" onclick=\"location.href='profile_admin.html'\" class=\"w3-button w3-theme-d2\" style=\"width:100%\">\n");
      out.write("                                <i class=\"fa fa-user\"></i> View Profile</button>\n");
      out.write("                            <br>\n");
      out.write("                            <br>\n");
      out.write("                            <button type=\"button\" class=\"w3-button w3-theme-d2\" style=\"width:100%\">\n");
      out.write("                                <i class=\"fa fa-download\"></i> Download (XML)</button>\n");
      out.write("                        </td>\n");
      out.write("                    </table>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"w3-container w3-card w3-white w3-margin\">\n");
      out.write("                    <table style=\"width: 100%\">\n");
      out.write("                        <td>\n");
      out.write("                            <p class=\"w3-center\">\n");
      out.write("                                <a href=\"profile_admin.html\">\n");
      out.write("                                    <img src=\"images/avatar3.png\" style=\"height:116px;width:116px\" alt=\"Avatar\">\n");
      out.write("                                </a>\n");
      out.write("                            </p>\n");
      out.write("                        </td>\n");
      out.write("                        <td class=\"w3-padding\">\n");
      out.write("                            <h4 class=\"w3-center\"><a href=\"user_profile.html\" class=\"w3-link\">Profile #2</a></h4>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-pencil fa-fw w3-margin-right w3-text-theme\"></i> Designer, UI</p>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-home fa-fw w3-margin-right w3-text-theme\"></i> London, UK</p>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme\"></i> April 1, 1988</p>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-envelope-open\"></i> Email: email@gmail.com</p>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-phone\"></i> Phone: +123456789</p>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-link\"></i> Website: website.com</p>\n");
      out.write("                            </p>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <div style=\"width:100%\">\n");
      out.write("                                <table style=\"width:100%\">\n");
      out.write("                                    <td style=\"width:100%\">\n");
      out.write("                                        <label class=\"w3-opacity-min\">Select User (XML) </label>\n");
      out.write("                                    </td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input id=\"check_2\" class=\"w3-check\" type=\"checkbox\">\n");
      out.write("                                    </td>\n");
      out.write("                                </table>\n");
      out.write("                            </div>\n");
      out.write("                            <button type=\"button\" onclick=\"location.href='profile_admin.html'\" class=\"w3-button w3-theme-d2\" style=\"width:100%\">\n");
      out.write("                                <i class=\"fa fa-user\"></i> View Profile</button>\n");
      out.write("                            <br>\n");
      out.write("                            <br>\n");
      out.write("                            <button type=\"button\" class=\"w3-button w3-theme-d2\" style=\"width:100%\">\n");
      out.write("                                <i class=\"fa fa-download\"></i> Download (XML)</button>\n");
      out.write("                        </td>\n");
      out.write("                    </table>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"w3-container w3-card w3-white w3-margin\">\n");
      out.write("                    <table style=\"width: 100%\">\n");
      out.write("                        <td>\n");
      out.write("                            <p class=\"w3-center\">\n");
      out.write("                                <a href=\"profile_admin.html\">\n");
      out.write("                                    <img src=\"images/avatar5.png\" style=\"height:116px;width:116px\" alt=\"Avatar\">\n");
      out.write("                                </a>\n");
      out.write("                            </p>\n");
      out.write("                        </td>\n");
      out.write("                        <td class=\"w3-padding\">\n");
      out.write("                            <h4 class=\"w3-center\"><a href=\"user_profile.html\" class=\"w3-link\">Profile #3</a></h4>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-pencil fa-fw w3-margin-right w3-text-theme\"></i> Designer, UI</p>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-home fa-fw w3-margin-right w3-text-theme\"></i> London, UK</p>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme\"></i> April 1, 1988</p>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-envelope-open\"></i> Email: email@gmail.com</p>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-phone\"></i> Phone: +123456789</p>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-link\"></i> Website: website.com</p>\n");
      out.write("                            </p>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <div style=\"width:100%\">\n");
      out.write("                                <table style=\"width:100%\">\n");
      out.write("                                    <td style=\"width:100%\">\n");
      out.write("                                        <label class=\"w3-opacity-min\">Select User (XML) </label>\n");
      out.write("                                    </td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input id=\"check_3\" class=\"w3-check\" type=\"checkbox\">\n");
      out.write("                                    </td>\n");
      out.write("                                </table>\n");
      out.write("                            </div>\n");
      out.write("                            <button type=\"button\" onclick=\"location.href='profile_admin.html'\" class=\"w3-button w3-theme-d2\" style=\"width:100%\">\n");
      out.write("                                <i class=\"fa fa-user\"></i> View Profile</button>\n");
      out.write("                            <br>\n");
      out.write("                            <br>\n");
      out.write("                            <button type=\"button\" class=\"w3-button w3-theme-d2\" style=\"width:100%\">\n");
      out.write("                                <i class=\"fa fa-download\"></i> Download (XML)</button>\n");
      out.write("                        </td>\n");
      out.write("                    </table>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"w3-container w3-card w3-white w3-margin\">\n");
      out.write("                    <table style=\"width: 100%\">\n");
      out.write("                        <td>\n");
      out.write("                            <p class=\"w3-center\">\n");
      out.write("                                <a href=\"profile_admin.html\">\n");
      out.write("                                    <img src=\"images/avatar6.png\" style=\"height:116px;width:116px\" alt=\"Avatar\">\n");
      out.write("                                </a>\n");
      out.write("                            </p>\n");
      out.write("                        </td>\n");
      out.write("                        <td class=\"w3-padding\">\n");
      out.write("                            <h4 class=\"w3-center\"><a href=\"user_profile.html\" class=\"w3-link\">Profile #4</a></h4>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-pencil fa-fw w3-margin-right w3-text-theme\"></i> Designer, UI</p>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-home fa-fw w3-margin-right w3-text-theme\"></i> London, UK</p>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme\"></i> April 1, 1988</p>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-envelope-open\"></i> Email: email@gmail.com</p>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-phone\"></i> Phone: +123456789</p>\n");
      out.write("                            <p>\n");
      out.write("                                <i class=\"fa fa-link\"></i> Website: website.com</p>\n");
      out.write("                            </p>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <div style=\"width:100%\">\n");
      out.write("                                <table style=\"width:100%\">\n");
      out.write("                                    <td style=\"width:100%\">\n");
      out.write("                                        <label class=\"w3-opacity-min\">Select User (XML) </label>\n");
      out.write("                                    </td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input id=\"check_4\" class=\"w3-check\" type=\"checkbox\">\n");
      out.write("                                    </td>\n");
      out.write("                                </table>\n");
      out.write("                            </div>\n");
      out.write("                            <button type=\"button\" onclick=\"location.href='profile_admin.html'\" class=\"w3-button w3-theme-d2\" style=\"width:100%\">\n");
      out.write("                                <i class=\"fa fa-user\"></i> View Profile</button>\n");
      out.write("                            <br>\n");
      out.write("                            <br>\n");
      out.write("                            <button type=\"button\" class=\"w3-button w3-theme-d2\" style=\"width:100%\">\n");
      out.write("                                <i class=\"fa fa-download\"></i> Download (XML)</button>\n");
      out.write("                        </td>\n");
      out.write("                    </table>\n");
      out.write("                </div>\n");
      out.write("                <!-- End Middle Column -->\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <!-- End Grid -->\n");
      out.write("    </div>\n");
      out.write("    <!-- End Page Container -->\n");
      out.write("    </div>\n");
      out.write("    <br>\n");
      out.write("    <br>\n");
      out.write("    <br>\n");
      out.write("    <!-- Footer -->\n");
      out.write("    <footer class=\"w3-container w3-theme-d5\">\n");
      out.write("        <table class=\"w3-opacity-min\" style=\"width:100%\">\n");
      out.write("            <td>\n");
      out.write("                <h5>WorkConnect</h5>\n");
      out.write("            </td>\n");
      out.write("            <td style=\"float:right\">\n");
      out.write("                <p>Made by Vasileios Papavasileiou & Vasileios Sakkas - Powered by\n");
      out.write("                    <a href=\"https://www.w3schools.com/w3css/default.asp\" target=\"_blank\">w3.css</a>\n");
      out.write("                </p>\n");
      out.write("            </td>\n");
      out.write("        </table>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        var user_count = 4;\n");
      out.write("        // Used to toggle the menu on smaller screens when clicking on the menu button\n");
      out.write("        function openNav() {\n");
      out.write("            var x = document.getElementById(\"navDemo\");\n");
      out.write("            if (x.className.indexOf(\"w3-show\") == -1) {\n");
      out.write("                x.className += \" w3-show\";\n");
      out.write("            } else {\n");
      out.write("                x.className = x.className.replace(\" w3-show\", \"\");\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function unselect_all() {\n");
      out.write("            for (var i = 1; i <= user_count; i++) {\n");
      out.write("                document.getElementById(\"check_\" + i).checked = false;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
