/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-09-23 23:38:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class profile_005fedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1534674664000L));
    _jspx_dependants.put("jar:file:/home/bill/Desktop/linkedin%20workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LinkedInClone/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153374282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html>\n");
      out.write("<title>WorkConnect - Home</title>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/w3.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/w3-theme-blue-grey.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/fonts/open_sans.ttf\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/font-awesome.min.css\">\n");
      out.write("<style>\n");
      out.write("    html,\n");
      out.write("    body,\n");
      out.write("    h1,\n");
      out.write("    h2,\n");
      out.write("    h3,\n");
      out.write("    h4,\n");
      out.write("    h5 {\n");
      out.write("        font-family: \"Open Sans\", sans-serif\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<body class=\"w3-theme-l5\">\n");
      out.write("    <!-- Navbar -->\n");
      out.write("    <div class=\"w3-top\">\n");
      out.write("        <div class=\"w3-bar w3-theme-d3 w3-left-align w3-large\">\n");
      out.write("            <a class=\"w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-large\" href=\"javascript:void(0);\"\n");
      out.write("                onclick=\"openNav()\">\n");
      out.write("                <i class=\"fa fa-bars\"></i>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"/LinkedInClone/UserServlet\" class=\"w3-bar-item w3-button w3-padding-large\">\n");
      out.write("\n");
      out.write("                WorkConnect\n");
      out.write("            </a>\n");
      out.write("            <a href=\"/LinkedInClone/UserServlet/logout\" class=\"w3-bar-item w3-button w3-hide-small w3-right w3-padding-large\">\n");
      out.write("                <i class=\"fa fa-sign-out\"></i>\n");
      out.write("                Log Out\n");
      out.write("            </a>\n");
      out.write("            <a href=\"/LinkedInClone/UserSettings\" class=\"w3-bar-item w3-button w3-hide-small w3-right w3-padding-large\">\n");
      out.write("                <i class=\"fa fa-gear\"></i>\n");
      out.write("                Settings\n");
      out.write("            </a>\n");
      out.write("            <a href=\"/LinkedInClone/UserProfile\" class=\"w3-bar-item w3-button w3-hide-small w3-right w3-padding-large\">\n");
      out.write("                <i class=\"fa fa-user\"></i>\n");
      out.write("                My Profile\n");
      out.write("            </a>\n");
      out.write("            <a href=\"/LinkedInClone/UserNotifications\" class=\"w3-bar-item w3-button w3-hide-small w3-right w3-padding-large\">\n");
      out.write("                <i class=\"fa fa-bell\"></i>\n");
      out.write("                Notifications\n");
      out.write("            </a>\n");
      out.write("            <a href=\"/LinkedInClone/UserMessages\" class=\"w3-bar-item w3-button w3-hide-small w3-right w3-padding-large\">\n");
      out.write("                <i class=\"fa fa-envelope\"></i>\n");
      out.write("                Messages\n");
      out.write("            </a>\n");
      out.write("            <a href=\"/LinkedInClone/UserJobs\" class=\"w3-bar-item w3-button w3-hide-small w3-right w3-padding-large\">\n");
      out.write("                <i class=\"fa fa-list\"></i>\n");
      out.write("                Jobs\n");
      out.write("            </a>\n");
      out.write("            <a href=\"/LinkedInClone/UserNetwork\" class=\"w3-bar-item w3-button w3-hide-small w3-right w3-padding-large\">\n");
      out.write("                <i class=\"fa fa-globe\"></i>\n");
      out.write("                Network\n");
      out.write("            </a>\n");
      out.write("            <a href=\"/LinkedInClone/UserServlet\" class=\"w3-bar-item w3-button w3-hide-small w3-right w3-padding-large\">\n");
      out.write("                <i class=\"fa fa-home\"></i>\n");
      out.write("                Home\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Navbar on small screens -->\n");
      out.write("    <div id=\"navDemo\" class=\"w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium w3-large\">\n");
      out.write("        <a href=\"/LinkedInClone/UserServlet\" class=\"w3-bar-item w3-button w3-padding-large\">Home</a>\n");
      out.write("        <a href=\"/LinkedInClone/UserNetwork\" class=\"w3-bar-item w3-button w3-padding-large\">Network</a>\n");
      out.write("        <a href=\"/LinkedInClone/UserJobs\" class=\"w3-bar-item w3-button w3-padding-large\">Jobs</a>\n");
      out.write("        <a href=\"/LinkedInClone/UserMessages\" class=\"w3-bar-item w3-button w3-padding-large\">Messages</a>\n");
      out.write("        <a href=\"/LinkedInClone/UserNotifications\" class=\"w3-bar-item w3-button w3-padding-large\">Notifications</a>\n");
      out.write("        <a href=\"/LinkedInClone/UserProfile\" class=\"w3-bar-item w3-button w3-padding-large\">My Profile</a>\n");
      out.write("        <a href=\"/LinkedInClone/UserSettings\" class=\"w3-bar-item w3-button w3-padding-large\">Settings</a>\n");
      out.write("        <a href=\"/LinkedInClone/UserServlet/logout\" class=\"w3-bar-item w3-button w3-padding-large\">Log Out</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Page Container -->\n");
      out.write("    <div class=\"w3-container w3-content\" style=\"max-width:66.%;margin-top:80px\">\n");
      out.write("        <!-- The Grid -->\n");
      out.write("        <div class=\"w3-row\">\n");
      out.write("        <form action=\"/LinkedInClone/UserProfile\" method=\"post\" enctype='multipart/form-data'>\n");
      out.write("\n");
      out.write("            <!-- Middle Column -->\n");
      out.write("            <div class=\"w3-col m4\">\n");
      out.write("\n");
      out.write("                <div class=\"w3-container w3-card w3-white w3-margin\">\n");
      out.write("                    <br>\n");
      out.write("                    <img name=\"profile_img\" id=\"profile_img\" src=\"/LinkedInClone/ImageServlet?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prof.getPath()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"Avatar\" style=\"width:100%\" class=\"w3-round-large w3-margin-bottom\">\n");
      out.write("                    <table>\n");
      out.write("                        <td>\n");
      out.write("                            <p class=\"w3-opacity-min\">Select and upload a new profile image.</p>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <button type=\"button\" onclick=\"image_upload();\" class=\"w3-button w3-theme-d2\">\n");
      out.write("                                <i class=\"fa fa-upload \"></i> Browse</button>\n");
      out.write("                            <input id='upload_button' type='file' name=\"image\" onchange=\"image_preview();\" hidden />\n");
      out.write("                        </td>\n");
      out.write("                    </table>\n");
      out.write("                    <hr class=\"w3-clear\">\n");
      out.write("                    <div class=\"w3-row w3-padding-8\" style=\"width:100%;\">\n");
      out.write("                        <input id=\"name\" name=\"name\" type=\"text\" placeholder=\"Name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prof.getName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"w3-border w3-padding\" style=\"width:100%;\" />\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"w3-row w3-padding-8\" style=\"width:100%;\">\n");
      out.write("                        <input id=\"surname\" name=\"surname\" type=\"text\" placeholder=\"Surname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prof.getSurname()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"w3-border w3-padding\" style=\"width:100%;\" />\n");
      out.write("                    </div>\n");
      out.write("                    <hr class=\"w3-clear\">\n");
      out.write("                    <div class=\"w3-row w3-padding-8\" style=\"width:100%;\">\n");
      out.write("                        <input id=\"description\" name=\"description\" type=\"text\" placeholder=\"Description\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prof.getJobTitle()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"w3-border w3-padding\" style=\"width:100%;\" />\n");
      out.write("                    </div>\n");
      out.write("                    <hr class=\"w3-clear\">\n");
      out.write("                    <h4>Contact Info</h4>\n");
      out.write("                    <div class=\"w3-row w3-padding-8\" style=\"width:100%;\">\n");
      out.write("                        <input name=\"telephone\" type=\"text\" placeholder=\"Phone\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prof.getTelephone()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"w3-border w3-padding\" style=\"width:100%;\" />\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- End Middle Column -->\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"w3-col m8\">\n");
      out.write("                <div class=\"w3-container w3-card w3-white w3-margin\">\n");
      out.write("                    <table style=\"width:100%;\">\n");
      out.write("                        <td>\n");
      out.write("                            <h4>Work Experience</h4>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <div style=\"float:right;\">\n");
      out.write("                                <input type=\"radio\" name=\"w_visibility\" value=\"Public\" style=\"vertical-align: sub\"\n");
      out.write("                                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prof.getExperiencePrivate()=='false'?'checked':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("> Public\n");
      out.write("                                <input type=\"radio\" name=\"w_visibility\" value=\"Private\" style=\"vertical-align: sub\"\n");
      out.write("                                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prof.getExperiencePrivate()=='true'?'checked':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\n");
      out.write("                                Private\n");
      out.write("                            </div>\n");
      out.write("                        </td>\n");
      out.write("                    </table>\n");
      out.write("                    <div name=\"work_wrapper\" id=\"work_wrapper\">\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <input type=\"hidden\" id=\"return_experience\" name=\"return_experience\"/>\n");
      out.write("                    ");
int numOfExperience = (Integer) request.getAttribute("num_of_experience");
      out.write("\n");
      out.write("                    <div class=\"w3-row w3-padding-8\" style=\"width:100%;\">\n");
      out.write("                        <button type=\"button\" onclick=\"add_work();\" class=\"w3-button w3-theme-d2 w3-margin-bottom\">\n");
      out.write("                            <i class=\"fa fa-plus\"></i> Add Entry</button>\n");
      out.write("                    </div>\n");
      out.write("                    <hr class=\"w3-clear\">\n");
      out.write("                    <table style=\"width:100%;\">\n");
      out.write("                        <td>\n");
      out.write("                            <h4>Education</h4>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <fdiv style=\"float:right;\">\n");
      out.write("                                <input type=\"radio\" name=\"e_visibility\" value=\"Public\" style=\"vertical-align: sub\"\n");
      out.write("                                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prof.getEducationPrivate()=='false'?'checked':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("> Public\n");
      out.write("                                <input type=\"radio\" name=\"e_visibility\" value=\"Private\" style=\"vertical-align: sub\"\n");
      out.write("                                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prof.getEducationPrivate()=='true'?'checked':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\n");
      out.write("                                Private\n");
      out.write("                            </div>\n");
      out.write("                        </td>\n");
      out.write("                    </table>\n");
      out.write("                    <div name=\"education_wrapper\" id=\"education_wrapper\">\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <input type=\"hidden\" id=\"return_education\" name=\"return_education\"/>\n");
      out.write("                    ");
int numOfEducation = (Integer) request.getAttribute("num_of_education");
      out.write("\n");
      out.write("                    <div class=\"w3-row w3-padding-8\" style=\"width:100%;\">\n");
      out.write("                        <button type=\"button\" onclick=\"add_education();\" class=\"w3-button w3-theme-d2 w3-margin-bottom\">\n");
      out.write("                            <i class=\"fa fa-plus\"></i> Add Entry</button>\n");
      out.write("                    </div>\n");
      out.write("                    <hr class=\"w3-clear\">\n");
      out.write("                    <table style=\"width:100%;\">\n");
      out.write("                        <td>\n");
      out.write("                            <h4>Skills</h4>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <div style=\"float:right;\">\n");
      out.write("                                <input type=\"radio\" name=\"s_visibility\" value=\"Public\" style=\"vertical-align: sub\"\n");
      out.write("                                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prof.getSkillsPrivate()=='false'?'checked':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("> Public\n");
      out.write("                                <input type=\"radio\" name=\"s_visibility\" value=\"Private\" style=\"vertical-align: sub\"\n");
      out.write("                                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prof.getSkillsPrivate()=='true'?'checked':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\n");
      out.write("                                Private\n");
      out.write("                            </div>\n");
      out.write("                        </td>\n");
      out.write("                    </table>\n");
      out.write("                    <div class=\"w3-row w3-padding-8\" style=\"width:100%;\">\n");
      out.write("                        <input name = \"skills\" type=\"text\" placeholder=\"Interests. Use a comma (,) to separate your different skills.\"\n");
      out.write("                            class=\"w3-border w3-padding\" style=\"width:100%;\" value=\"");
      out.print(request.getAttribute("skill_commas"));
      out.write("\"/>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"w3-row w3-padding-8\" style=\"width:100%;\">\n");
      out.write("                        <button type=\"button\" onclick=\"location.href='/LinkedInClone/UserProfile'\" class=\"w3-button w3-theme-d2 w3-margin-bottom\">\n");
      out.write("                            <i class=\"fa fa-arrow-left\"></i> Cancel</button>\n");
      out.write("                        <button type=\"submit\" onclick=\"check_input();\" class=\"w3-button w3-theme-d2 w3-margin-bottom\">\n");
      out.write("                            <i class=\"fa fa-save\"></i> Save</button>\n");
      out.write("                        <input id=\"error_message\" class=\"w3-opacity-min\" type=\"text\" value=\"\" style=\"border: 0;background-color: inherit; color:red;font-weight: bold\"\n");
      out.write("                            readonly>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("\n");
      out.write("                <!-- End Middle Column -->\n");
      out.write("            </div>\n");
      out.write("\t\t</form>\n");
      out.write("        </div>\n");
      out.write("        <!-- End Grid -->\n");
      out.write("    </div>\n");
      out.write("    <!-- End Page Container -->\n");
      out.write("    </div>\n");
      out.write("    <br>\n");
      out.write("    <br>\n");
      out.write("    <br>\n");
      out.write("    <!-- Footer -->\n");
      out.write("    <footer class=\"w3-container w3-theme-d5\">\n");
      out.write("        <table class=\"w3-opacity-min\" style=\"width:100%\">\n");
      out.write("            <td>\n");
      out.write("                <h5>WorkConnect</h5>\n");
      out.write("            </td>\n");
      out.write("            <td style=\"float:right\">\n");
      out.write("                <p>Made by Vasileios Papavasileiou & Vasileios Sakkas - Powered by\n");
      out.write("                    <a href=\"https://www.w3schools.com/w3css/default.asp\" target=\"_blank\">w3.css</a>\n");
      out.write("                </p>\n");
      out.write("            </td>\n");
      out.write("        </table>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        // Used to toggle the menu on smaller screens when clicking on the menu button\n");
      out.write("        function openNav() {\n");
      out.write("            var x = document.getElementById(\"navDemo\");\n");
      out.write("            if (x.className.indexOf(\"w3-show\") == -1) {\n");
      out.write("                x.className += \" w3-show\";\n");
      out.write("            } else {\n");
      out.write("                x.className = x.className.replace(\" w3-show\", \"\");\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function image_upload() {\n");
      out.write("            document.getElementById('upload_button').click();\n");
      out.write("        }\n");
      out.write("\n");
      out.write("\n");
      out.write("        function image_preview() {\n");
      out.write("            var selected_image = document.getElementById('upload_button').files[0];\n");
      out.write("            document.getElementById('profile_img').src = window.URL.createObjectURL(selected_image);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        var education_counter = ");
      out.print(numOfEducation);
      out.write(", work_counter = ");
      out.print(numOfExperience);
      out.write(";\n");
      out.write("        function add_work() {\n");
      out.write("            var work_title_list = [], work_from_list = [], work_description_list = [];\n");
      out.write("            for (var i = 1; i <= work_counter; i++) {\n");
      out.write("                var work_title = 'work_title_%num%'.replace('%num%', i),\n");
      out.write("                    work_from = 'work_from_%num%'.replace('%num%', i),\n");
      out.write("                    work_description = 'work_description_%num%'.replace('%num%', i);\n");
      out.write("\n");
      out.write("                if (document.getElementById(work_title)) {\n");
      out.write("                    work_title_list.push(document.getElementById(work_title).value);\n");
      out.write("                    work_from_list.push(document.getElementById(work_from).value);\n");
      out.write("                    work_description_list.push(document.getElementById(work_description).value);\n");
      out.write("                }\n");
      out.write("                else {\n");
      out.write("                    work_title_list.push('');\n");
      out.write("                    work_from_list.push('');\n");
      out.write("                    work_description_list.push('');\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            work_counter += 1;\n");
      out.write("            var field_to_add = '<div name=\"work_title_wrapper_%num%\" id=\"work_title_wrapper_%num%\" class=\"w3-row\" style=\"width:100%;\">\\n<hr class=\"w3-clear\">\\n<input name=\"work_title_%num%\" id=\"work_title_%num%\" type=\"text\" placeholder=\"Title\" class=\"w3-border w3-padding\" style=\"width:40%;\" />\\n<input name=\"work_from_%num%\" id=\"work_from_%num%\" placeholder=\"From\" type=\"text\" class=\"w3-border w3-padding\" style=\"width: 29%\" onfocus=\"(this.type=\\'date\\')\"onblur=\"(this.type=\\'text\\')\">\\n<input name=\"work_to_%num%\" id=\"work_to_%num%\" placeholder=\"To\" type=\"text\" class=\"w3-border w3-padding\" style=\"width: 29%\" onfocus=\"(this.type=\\'date\\')\"onblur=\"(this.type=\\'text\\')\">\\n</div>\\n<div name=\"work_description_wrapper_%num%\" id=\"work_description_wrapper_%num%\" class=\"w3-row w3-padding-8\" style=\"width:100%;\">\\n<input name=\"work_description_%num%\" id=\"work_description_%num%\" type=\"text\" placeholder=\"Description\" class=\"w3-border w3-padding\" style=\"width:100%;\" />\\n</div><div id=\"work_remove_wrapper_%num%\" class=\"w3-row w3-padding-8\" style=\"width:100%;\"><button name=\"work_remove_%num%\" id=\"work_remove_%num%\" type=\"button\" onclick=\"remove_work(this.id);\" class=\"w3-button w3-theme-d2\"><i class=\"fa fa-minus\"></i> Remove Entry</button></div>'.replace(/%num%/g, work_counter);\n");
      out.write("            document.getElementById('work_wrapper').innerHTML += field_to_add;\n");
      out.write("\n");
      out.write("            for (var i = 1; i < work_counter; i++) {\n");
      out.write("                var work_title = 'work_title_%num%'.replace('%num%', i),\n");
      out.write("                    work_from = 'work_from_%num%'.replace('%num%', i),\n");
      out.write("                    work_description = 'work_description_%num%'.replace('%num%', i);\n");
      out.write("\n");
      out.write("                if (document.getElementById(work_title)) {\n");
      out.write("                    document.getElementById(work_title).value = work_title_list[i - 1];\n");
      out.write("                    document.getElementById(work_from).value = work_from_list[i - 1];\n");
      out.write("                    document.getElementById(work_description).value = work_description_list[i - 1];\n");
      out.write("                }\n");
      out.write("            }        \n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function remove_work(id) {\n");
      out.write("            var id_num = id.split('_').pop();\n");
      out.write("            var work_title_to_remove = \"work_title_wrapper_%num%\".replace(\"%num%\", id_num),\n");
      out.write("                work_description_to_remove = \"work_description_wrapper_%num%\".replace(\"%num%\", id_num),\n");
      out.write("                work_remove_wrapper = 'work_remove_wrapper_%num%'.replace(\"%num%\", id_num);\n");
      out.write("            document.getElementById(work_title_to_remove).outerHTML = \"\";\n");
      out.write("            document.getElementById(work_description_to_remove).outerHTML = \"\";\n");
      out.write("            document.getElementById(work_remove_wrapper).outerHTML = \"\";\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function add_education() {\n");
      out.write("            var education_title_list = [], education_from_list = [], education_description_list = [];\n");
      out.write("            for (var i = 1; i <= education_counter; i++) {\n");
      out.write("                var education_title = 'education_title_%num%'.replace('%num%', i),\n");
      out.write("                    education_from = 'education_from_%num%'.replace('%num%', i),\n");
      out.write("                    education_description = 'education_description_%num%'.replace('%num%', i);\n");
      out.write("\n");
      out.write("                if (document.getElementById(education_title)) {\n");
      out.write("                    education_title_list.push(document.getElementById(education_title).value);\n");
      out.write("                    education_from_list.push(document.getElementById(education_from).value);\n");
      out.write("                    education_description_list.push(document.getElementById(education_description).value);\n");
      out.write("                }\n");
      out.write("                else {\n");
      out.write("                    education_title_list.push('');\n");
      out.write("                    education_from_list.push('');\n");
      out.write("                    education_description_list.push('');\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            education_counter += 1;\n");
      out.write("            var field_to_add = '<div name=\"education_title_wrapper_%num%\" id=\"education_title_wrapper_%num%\" class=\"w3-row\" style=\"width:100%;\">\\n<hr class=\"w3-clear\">\\n<input name=\"education_title_%num%\" id=\"education_title_%num%\" type=\"text\" placeholder=\"Title\" class=\"w3-border w3-padding\" style=\"width:40.5%;\" />\\n<input name=\"education_from_%num%\" id=\"education_from_%num%\" placeholder=\"From\" type=\"text\" class=\"w3-border w3-padding\" style=\"width: 29%\" onfocus=\"(this.type=\\'date\\')\"onblur=\"(this.type=\\'text\\')\">\\n<input name=\"education_to_%num%\" id=\"education_to_%num%\" placeholder=\"To\" type=\"text\" class=\"w3-border w3-padding\" style=\"width: 29%\" onfocus=\"(this.type=\\'date\\')\"onblur=\"(this.type=\\'text\\')\">\\n</div>\\n<div name=\"education_description_wrapper_%num%\" id=\"education_description_wrapper_%num%\" class=\"w3-row w3-padding-8\" style=\"width:100%;\">\\n<input name=\"education_description_%num%\" id=\"education_description_%num%\" type=\"text\" placeholder=\"Description\" class=\"w3-border w3-padding\" style=\"width:100%;\" />\\n</div><div name=\"education_remove_wrapper_%num%\" id=\"education_remove_wrapper_%num%\" class=\"w3-row w3-padding-8\" style=\"width:100%;\"><button name=\"education_remove_%num%\" id=\"education_remove_%num%\" type=\"button\" onclick=\"remove_education(this.id);\" class=\"w3-button w3-theme-d2\"><i class=\"fa fa-minus\"></i> Remove Entry</button></div>'.replace(/%num%/g, education_counter);\n");
      out.write("            document.getElementById('education_wrapper').innerHTML += field_to_add;\n");
      out.write("\n");
      out.write("            for (var i = 1; i < education_counter; i++) {\n");
      out.write("                var education_title = 'education_title_%num%'.replace('%num%', i),\n");
      out.write("                    education_from = 'education_from_%num%'.replace('%num%', i),\n");
      out.write("                    education_description = 'education_description_%num%'.replace('%num%', i);\n");
      out.write("\n");
      out.write("                if (document.getElementById(education_title)) {\n");
      out.write("                    document.getElementById(education_title).value = education_title_list[i - 1];\n");
      out.write("                    document.getElementById(education_from).value = education_from_list[i - 1];\n");
      out.write("                    document.getElementById(education_description).value = education_description_list[i - 1];\n");
      out.write("                }\n");
      out.write("            }        \n");
      out.write("        }\n");
      out.write("\n");
      out.write("\n");
      out.write("        function remove_education(id) {\n");
      out.write("            var id_num = id.split('_').pop();\n");
      out.write("            var education_title_to_remove = \"education_title_wrapper_%num%\".replace(\"%num%\", id_num),\n");
      out.write("                education_description_to_remove = \"education_description_wrapper_%num%\".replace(\"%num%\", id_num),\n");
      out.write("                education_remove_wrapper = 'education_remove_wrapper_%num%'.replace(\"%num%\", id_num);\n");
      out.write("            document.getElementById(education_title_to_remove).outerHTML = \"\";\n");
      out.write("            document.getElementById(education_description_to_remove).outerHTML = \"\";\n");
      out.write("            document.getElementById(education_remove_wrapper).outerHTML = \"\";\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function check_input() {\n");
      out.write("        \tdocument.getElementById(\"return_experience\").value = work_counter;\n");
      out.write("        \tdocument.getElementById(\"return_education\").value = education_counter;\n");
      out.write("            var error = false;\n");
      out.write("            for (var i = 1; i <= work_counter; i++) {\n");
      out.write("\n");
      out.write("                var work_title = 'work_title_%num%'.replace('%num%', i),\n");
      out.write("                    work_from = 'work_from_%num%'.replace('%num%', i),\n");
      out.write("                    work_description = 'work_description_%num%'.replace('%num%', i);\n");
      out.write("\n");
      out.write("                if (document.getElementById(work_title)) {\n");
      out.write("                    if (document.getElementById(work_title).value == \"\") {\n");
      out.write("                        document.getElementById(work_title).setCustomValidity(\"Invalid field.\");\n");
      out.write("                        document.getElementById('error_message').value = \"Missing required fields.\";\n");
      out.write("                        error = true;\n");
      out.write("                    }\n");
      out.write("                    if (document.getElementById(work_from).value == \"\") {\n");
      out.write("                        document.getElementById(work_from).setCustomValidity(\"Invalid field.\");\n");
      out.write("                        document.getElementById('error_message').value = \"Missing required fields.\";\n");
      out.write("                        error = true;\n");
      out.write("                    }\n");
      out.write("                    if (document.getElementById(work_description).value == \"\") {\n");
      out.write("                        document.getElementById(work_description).setCustomValidity(\"Invalid field.\");\n");
      out.write("                        document.getElementById('error_message').value = \"Missing required fields.\";\n");
      out.write("                        error = true;\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            for (var i = 1; i <= education_counter; i++) {\n");
      out.write("                var education_title = 'education_title_%num%'.replace('%num%', i),\n");
      out.write("                    education_from = 'education_from_%num%'.replace('%num%', i),\n");
      out.write("                    education_description = 'education_description_%num%'.replace('%num%', i);\n");
      out.write("\n");
      out.write("                if (document.getElementById(education_title)) {\n");
      out.write("                    if (document.getElementById(education_title).value == \"\") {\n");
      out.write("                        document.getElementById(education_title).setCustomValidity(\"Invalid field.\");\n");
      out.write("                        document.getElementById('error_message').value = \"Missing required fields.\";\n");
      out.write("                        error = true;\n");
      out.write("                    }\n");
      out.write("                    if (document.getElementById(education_from).value == \"\") {\n");
      out.write("                        document.getElementById(education_from).setCustomValidity(\"Invalid field.\");\n");
      out.write("                        document.getElementById('error_message').value = \"Missing required fields.\";\n");
      out.write("                        error = true;\n");
      out.write("                    }\n");
      out.write("                    if (document.getElementById(education_description).value == \"\") {\n");
      out.write("                        document.getElementById(education_description).setCustomValidity(\"Invalid field.\");\n");
      out.write("                        document.getElementById('error_message').value = \"Missing required fields.\";\n");
      out.write("                        error = true;\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            if (document.getElementById('name').value == \"\") {\n");
      out.write("                document.getElementById('name').setCustomValidity(\"Invalid field.\");\n");
      out.write("                document.getElementById('error_message').value = \"Missing required fields.\";\n");
      out.write("                error = true;\n");
      out.write("            }\n");
      out.write("            if (document.getElementById('surname').value == \"\") {\n");
      out.write("                document.getElementById('surname').setCustomValidity(\"Invalid field.\");\n");
      out.write("                document.getElementById('error_message').value = \"Missing required fields.\";\n");
      out.write("                error = true;\n");
      out.write("            }\n");
      out.write("            if (document.getElementById('description').value == \"\") {\n");
      out.write("                document.getElementById('description').setCustomValidity(\"Invalid field.\");\n");
      out.write("                document.getElementById('error_message').value = \"Missing required fields.\";\n");
      out.write("                error = true;\n");
      out.write("            }\n");
      out.write("            if (error == false) {\n");
      out.write("                document.getElementById('error_message').value = \"\";\n");
      out.write("                location.href = \"profile.html\";\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /user/profile_edit.jsp(143,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/user/profile_edit.jsp(143,20) '${prof.getExperiences()}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${prof.getExperiences()}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /user/profile_edit.jsp(143,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("experience");
    // /user/profile_edit.jsp(143,20) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVarStatus("loop");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                        <div name=\"work_title_wrapper_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"work_title_wrapper_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"w3-row w3-padding-8\" style=\"width:100%;\">\n");
          out.write("                            <input name=\"work_title_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"work_title_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" type=\"text\" placeholder=\"Title\" class=\"w3-border w3-padding\"\n");
          out.write("                                style=\"width:40%\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${experience.getTitle()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\n");
          out.write("                            <input name=\"work_from_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"work_from_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" placeholder=\"From\" type=\"text\" class=\"w3-border w3-padding\"\n");
          out.write("                                style=\"width: 29%\" onfocus=\"(this.type='date')\" onblur=\"(this.type='text')\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${experience.getFrom()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\n");
          out.write("                            <input name=\"work_to_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"work_to_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" placeholder=\"To\" type=\"text\" class=\"w3-border w3-padding\"\n");
          out.write("                                style=\"width: 29%\" onfocus=\"(this.type='date')\" onblur=\"(this.type='text')\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${experience.getTo()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\n");
          out.write("                        </div>\n");
          out.write("                        <div name=\"work_description_wrapper_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"work_description_wrapper_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"w3-row w3-padding-8\"\n");
          out.write("                            style=\"width:100%;\">\n");
          out.write("                            <input name =\"work_description_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"work_description_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" type=\"text\" placeholder=\"Description\" class=\"w3-border w3-padding\"\n");
          out.write("                                style=\"width:100%;\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${experience.getDescription()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\n");
          out.write("                        </div>\n");
          out.write("                        <div name=\"work_remove_wrapper_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id='work_remove_wrapper_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("' class=\"w3-row w3-padding-8\" style=\"width:100%;\">\n");
          out.write("                            <button name=\"work_remove_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"work_remove_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" type=\"button\" onclick=\"remove_work(this.id);\"\n");
          out.write("                                class=\"w3-button w3-theme-d2\">\n");
          out.write("                                <i class=\"fa fa-minus\"></i> Remove Entry</button>\n");
          out.write("                        </div>\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /user/profile_edit.jsp(186,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/user/profile_edit.jsp(186,20) '${prof.getEducations()}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${prof.getEducations()}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /user/profile_edit.jsp(186,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("education");
    // /user/profile_edit.jsp(186,20) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVarStatus("loop");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                        <div name=\"education_title_wrapper_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"education_title_wrapper_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"w3-row w3-padding-8\" style=\"width:100%;\">\n");
          out.write("                            <input name=\"education_title_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"education_title_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" type=\"text\" placeholder=\"Title\" class=\"w3-border w3-padding\"\n");
          out.write("                                style=\"width:40%\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${education.getTitle()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\n");
          out.write("                            <input name=\"education_from_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"education_from_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" placeholder=\"From\" type=\"text\" class=\"w3-border w3-padding\"\n");
          out.write("                                style=\"width: 29%\" onfocus=\"(this.type='date')\" onblur=\"(this.type='text')\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${education.getFrom()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\n");
          out.write("                            <input name=\"education_to_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"education_to_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" placeholder=\"To\" type=\"text\" class=\"w3-border w3-padding\"\n");
          out.write("                                style=\"width: 29%\" onfocus=\"(this.type='date')\" onblur=\"(this.type='text')\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${education.getTo()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\n");
          out.write("                        </div>\n");
          out.write("                        <div name=\"education_description_wrapper_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"education_description_wrapper_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"w3-row w3-padding-8\"\n");
          out.write("                            style=\"width:100%;\">\n");
          out.write("                            <input name =\"education_description_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"education_description_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" type=\"text\" placeholder=\"Description\" class=\"w3-border w3-padding\"\n");
          out.write("                                style=\"width:100%;\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${education.getDescription()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\n");
          out.write("                        </div>\n");
          out.write("                        <div name=\"education_remove_wrapper_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id='education_remove_wrapper_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("' class=\"w3-row w3-padding-8\" style=\"width:100%;\">\n");
          out.write("                            <button name=\"education_remove_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"education_remove_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" type=\"button\" onclick=\"remove_education(this.id);\"\n");
          out.write("                                class=\"w3-button w3-theme-d2\">\n");
          out.write("                                <i class=\"fa fa-minus\"></i> Remove Entry</button>\n");
          out.write("                        </div>\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }
}
